name: C CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed

    # Define a matrix to run the job for each project
    strategy:
      matrix:
        project: [ano_bisiesto]

    # Set the working directory for all steps in this job
    defaults:
      run:
        working-directory: ${{ matrix.project }}

    # Define the steps to build, test, and analyze the project
    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    # Cache build artifacts to speed up subsequent runs
    - name: Cache Sonar wrapper
      id: cache-wrapper
      uses: actions/cache@v4
      with:
        path: build-wrapper-linux-x86
        key: sonar-wrapper-v1

    # Set up C/C++ environment
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov unzip curl
        
    # Download and set up SonarQube Scanner
#    - name: Download Sonar build-wrapper
#      if: steps.cache-wrapper.outputs.cache-hit != 'true'
#      run: |
#        curl -sSLo build-wrapper.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
#        unzip build-wrapper.zip

    - name: Install Build Wrapper
      uses: SonarSource/sonarqube-scan-action/install-build-wrapper@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0

    # Build the project with build-wrapper to capture compilation data
    - name: Run Build Wrapper
      run: |
        rm -rf ${{ env.BUILD_WRAPPER_OUT_DIR }}
        build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make clean build

#    - name: Build with wrapper
#      run: |
#        rm -rf bw-output
#        mkdir bw-output
#        ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 \
#          --out-dir bw-output \
#        make clean build
# /usr/bin/gcc -c $(find src tests -name "*.c") -Isrc -Itests

    - name: Run tests
      run: |
        make test
        #ls -la
        #cat bw-output/compile_commands.json
        #cat bw-output/build-wrapper-dump.json

    # Generate coverage data
    - name: Generate coverage report
      run: make coverage-report

    # Run SonarQube scan
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          --define "sonar.cfamily.compile-commands=./${{ matrix.project }}/${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
          -Dsonar.organization=unarix
          -Dsonar.projectKey=${{ matrix.project }}
          -Dsonar.sources=src
          -Dsonar.tests=tests
          -Dsonar.projectBaseDir=./${{ matrix.project }}
